config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :locations
  #get 'home/index'
   root 'home#index' 
   get 'home/about'

    resources :locations do
      resources :articles, only: [:new, :create, :destroy]
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get("/", { :controller => "articles", :action => "index" })
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :location
  has_one_attached :image

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :articles, dependent: :destroy
  belongs_to :user
end

app/models/place.rb
class Place < ApplicationRecord
  # talks to the "places" table

end

app/models/post.rb
class Post < ApplicationRecord
  # talks to the "posts" table
  belongs_to :location 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :locations

        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_location
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def new
    @article = @location.articles.build
  end

  def create
    @article = @location.articles.build(article_params)
    if @article.save
      redirect_to @location, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @article = @location.articles.find(params[:id])
    if @article
      @article.destroy
      redirect_to @location, notice: 'Article was successfully destroyed.'
    else
      redirect_to @location, notice: 'Article not found.'
    end
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
    @location = Location.find(params[:id])
  end

  # GET /locations/new
  def new
    @location = current_user.locations.build
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = current_user.locations.build(location_params)

    if @location.save
      redirect_to @location, notice: "Location was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: "Location was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to locations_url, notice: "Location was successfully destroyed."
  end

  def correct_user
    @location = current_user.locations.find_by(id: params[:id])
    redirect_to location_path, notice: "Not Authorized To Edit This Location" if @location.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def location_params
    params.require(:location).permit(:City_name, :Country_name, :When, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_location

  def new
    @post = @location.posts.build
  end

  def create
    @post = @location.posts.build(post_params)
    if @post.save
      redirect_to @location, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @post = @location.posts.find(params[:id])
    @post.destroy
    redirect_to @location, notice: 'Post was successfully destroyed.'
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<div class="container mt-4">
  <h1 class="mb-4">New Article</h1>

  <%= form_with(model: [@location, @article], html: { class: 'mb-3', multipart: true }) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :date %>
      <%= form.date_field :date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: 'form-control' %>
    </div>

    <%= form.submit 'Create Article', class: 'btn btn-primary' %>
  <% end %>

  <%= link_to 'Back', @location, class: 'btn btn-secondary mt-3' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

<%= link_to 'Ali Travel List', root_path , class:'navbar-brand' %> 

 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      <%= link_to 'About Me', home_about_path, class:'nav-link'%>
       </li>


<li class="nav-item">
      <%= link_to 'Show Locations', locations_path, class:'nav-link'%>
       </li>


      <% if user_signed_in? %>

      <li class="nav-item">
      <%= link_to "New location", new_location_path, class:'nav-link'%>
       </li>

        <li class="nav-item">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link'%>

       </li>

       <li class="nav-item">
      <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link'%>
       </li>

       <% else %>

       <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link'%>
       </li>

       <li class="nav-item">
      <%= link_to 'Sign In', new_user_session_path, class:'nav-link'%>
       </li>

       <% end %>
      
      
    </ul>
    
  </div>
</nav>

app/views/home/about.html.erb
<div class="container mt-4">
  <h1 class="mb-4">About Me</h1>

  <p class="mb-3">Hello, my name is Ali. I am a travel enthusiast and I have created this website to share my travel experiences. I have visited various cities and countries, and in this website, I will be sharing my experiences, pictures, and articles about these places. I hope you enjoy reading about my travels as much as I enjoyed experiencing them.</p>

  <p class="mb-3">Feel free to explore the locations I have visited and read the articles I have written. Thank you for visiting my website!</p>
</div>

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1 class="mb-4">Welcome to Ali's Travel List!</h1>
      <p class="mb-4">Explore the world through the eyes of a passionate traveler.</p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col">
      <h2 class="mb-3">Discover Amazing Locations</h2>
      <p>Get inspired by the diverse range of locations I've visited, from vibrant cities to serene landscapes. Each location page provides essential information, stunning photographs, and articles that capture the essence of the place. Embark on a virtual adventure and start planning your next trip today!</p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col">
      <h2 class="mb-3">Engaging Articles</h2>
      <p>Dive into my collection of engaging articles, where I share detailed travel guides, insider tips, personal anecdotes, and recommendations. Whether you're an experienced globetrotter or a first-time traveler, you'll find valuable insights and inspiration to enhance your own travel experiences.</p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col">
      <h2 class="mb-3">Join the Journey</h2>
      <p>Stay connected with Ali's Travel List by subscribing to our newsletter. You'll receive updates on new destinations, articles, and exclusive travel tips straight to your inbox. Don't miss out on the opportunity to be part of this incredible journey!</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Ali's Travel List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>

  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <% if location.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :City_name %>
    <%= form.text_field :City_name, class: 'form-control' %>
  </div>

 <div class="form-group">
    
    <%= form.number_field :user_id, id: :location_user_id, value: current_user.id, class: 'form-control', type: :hidden %>
  </div>

  <div class="form-group">
    <%= form.label :Country_name %>
    <%= form.text_field :Country_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :When %>
    <%= form.date_field :When, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p>
    <strong>City name:</strong>
<%= link_to location.City_name, location_path(location) %>
  </p>


</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render "form", location: @location %>

<br>

<div>
  <%= link_to "Show this location", @location %> |
  <%= link_to "Back to locations", locations_path %>
</div>

app/views/locations/index.html.erb
<div class="container mt-4">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="mb-4">Locations</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>City</th>
        <th>Country</th>
        <th>Date</th>
        <th>User Id</th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>

      <% if location.user == current_user %>
        <tr>
          <td><%= link_to location.City_name, location %></td> 
          <td><%= location.Country_name %></td>
          <td><%= location.When %></td>
          <td><%= location.user_id %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New location", new_location_path, class: 'btn btn-primary' %>
</div>

app/views/locations/new.html.erb
<div class="container mt-4">
  <h1>New location</h1>

  <%= render "form", location: @location %>
  <br>
  <div>
    <%= link_to "Back to locations", locations_path %>
  </div>
</div>

app/views/locations/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <h2><%= @location.City_name %></h2>
      <p><strong>Country name:</strong> <%= @location.Country_name %></p>
      <p><strong>When:</strong> <%= @location.When %></p>

      <div class="d-flex justify-content-between align-items-center mt-2 mb-4">
        <div>
          <%= link_to 'Edit this location', edit_location_path(@location), class: 'btn btn-outline-secondary mr-2' %>
          <%= link_to 'Back to locations', locations_path, class: 'btn btn-outline-secondary' %>
        </div>
        <%= button_to 'Destroy this location', @location, method: :delete, class: 'btn btn-outline-danger' %>
      </div>

      <% if user_signed_in? %>
        <%= link_to 'New Article', new_location_article_path(@location), class: 'btn btn-outline-secondary mt-3' %>
      <% end %>

      <h3 class="mt-4">Articles</h3>

      <div class="row">
        <% @location.articles.each_slice(3) do |articles| %>
          <% articles.each do |article| %>
            <div class="col-md-4">
              <div class="border rounded p-3 mt-3">
                <h4><%= article.title %></h4>
                <p class="text-muted"><%= article.date %></p>
                <% if article.image.attached? %>
                  <%= image_tag article.image.variant(resize: '300x200'), class: 'img-fluid' %>
                <% else %>
                  <%= image_tag 'default_image.png', class: 'placeholder-image img-fluid' %>
                <% end %>
                <p><%= article.description %></p>

                <% if user_signed_in? %>
                  <%= button_to 'Delete Article', location_article_path(@location, article), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: [@location, @post]) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <%= form.submit 'Create Post' %>
<% end %>

<%= link_to 'Back', @location %>